-- AlterTable
ALTER TABLE "public"."Membership" ADD COLUMN     "accountHolder" TEXT,
ADD COLUMN     "address" TEXT,
ADD COLUMN     "annualFee" DOUBLE PRECISION,
ADD COLUMN     "bankName" TEXT,
ADD COLUMN     "biography" TEXT,
ADD COLUMN     "danceStyle" TEXT,
ADD COLUMN     "dateOfBirth" TIMESTAMP(3),
ADD COLUMN     "experience" TEXT,
ADD COLUMN     "iban" TEXT,
ADD COLUMN     "message" TEXT,
ADD COLUMN     "occupation" TEXT,
ADD COLUMN     "paymentDay" INTEGER,
ADD COLUMN     "paymentStatus" TEXT DEFAULT 'ACTIVE',
ADD COLUMN     "photo" TEXT,
ADD COLUMN     "postalCode" TEXT,
ADD COLUMN     "sepaMandateFile" TEXT,
ADD COLUMN     "sepaMandateReference" TEXT,
ADD COLUMN     "socialLinks" JSONB,
ADD COLUMN     "stageName" TEXT,
ALTER COLUMN "gender" DROP NOT NULL,
ALTER COLUMN "membershipType" DROP NOT NULL;
